import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("ave", {
  getEngineInfo: () => ipcRenderer.invoke("engine:info"),
  getRecentProjects: () => ipcRenderer.invoke("recent:list"),
  openProject: () => ipcRenderer.invoke("project:open"),
  readProject: (path: string) => ipcRenderer.invoke("project:read", path),
  saveProject: (payload: { path?: string | null; text: string }) => ipcRenderer.invoke("project:save", payload),
  saveProjectAs: (payload: { text: string }) => ipcRenderer.invoke("project:saveAs", payload),
  validateJson: (payload: { text: string }) => ipcRenderer.invoke("engine:validate", payload),
  repairJson: (payload: { text: string }) => ipcRenderer.invoke("engine:repair", payload),
  aiGenerate: (payload: { prompt: string }) => ipcRenderer.invoke("engine:aiGenerate", payload),
  youtubeShort: (payload: { prompt: string; style?: string | null }) => ipcRenderer.invoke("engine:youtubeShort", payload),
  contentGenerate: (payload: { prompt: string; mode: string; tone?: string | null; style?: string | null; existingPlan?: string | null; regenerate?: string | null; locks?: string[] | null; approved?: boolean | null }) => ipcRenderer.invoke("engine:contentGenerate", payload),
  autonomousPipeline: (payload: unknown) => ipcRenderer.invoke("engine:autonomousPipeline", payload),
  beginnerPickMedia: () => ipcRenderer.invoke("beginner:pickMedia"),
  beginnerPickImageFolder: () => ipcRenderer.invoke("beginner:pickImageFolder"),
  beginnerPickAssetFolder: () => ipcRenderer.invoke("beginner:pickAssetFolder"),
  beginnerPickMusic: () => ipcRenderer.invoke("beginner:pickMusic"),
  beginnerPickLogo: () => ipcRenderer.invoke("beginner:pickLogo"),
  beginnerAutoTemplate: (payload: unknown) => ipcRenderer.invoke("beginner:autoTemplate", payload),
  contentApprove: (payload: { planPath: string; section?: string | null; status?: string | null }) => ipcRenderer.invoke("engine:contentApprove", payload),
  createTemplate: (payload: { template: string }) => ipcRenderer.invoke("engine:template", payload),
  addCaptions: (payload: { text: string; transcriptPath: string; mode: string; style: string }) => ipcRenderer.invoke("engine:addCaptions", payload),
  runDirector: (payload: { text: string; projectPath?: string | null; goal: string; preserve?: string[] }) => ipcRenderer.invoke("engine:director", payload),
  generateStoryboard: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("engine:storyboard", payload),
  analyzeAssets: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("engine:assetAnalyze", payload),
  resolveBroll: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("engine:resolveBroll", payload),
  listHistory: (payload: { projectPath?: string | null }) => ipcRenderer.invoke("history:list", payload),
  rollbackHistory: (payload: { projectPath: string; versionId: string }) => ipcRenderer.invoke("history:rollback", payload),
  exportPackage: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("package:export", payload),
  openPackage: () => ipcRenderer.invoke("package:open"),
  listPlugins: () => ipcRenderer.invoke("plugin:list"),
  initPlugin: (payload: { name: string; type: string }) => ipcRenderer.invoke("plugin:init", payload),
  realtimePreview: (payload: { text: string; projectPath?: string | null; time?: number; sceneId?: string | null; qualityMode?: string; layerMode?: string }) => ipcRenderer.invoke("engine:realtimePreview", payload),
  interactivePreview: (payload: { text: string; projectPath?: string | null; qualityMode?: string; scope?: string; sceneId?: string | null }) => ipcRenderer.invoke("engine:interactivePreview", payload),
  qualityCheck: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("engine:qualityCheck", payload),
  finalPreflight: (payload: { text: string; projectPath?: string | null; previewVideo?: string | null; format?: string }) => ipcRenderer.invoke("engine:finalPreflight", payload),
  repairPreflight: (payload: { text: string; projectPath?: string | null; previewVideo?: string | null; format?: string; mode?: string; issueId?: string | null }) => ipcRenderer.invoke("engine:repairPreflight", payload),
  projectManifest: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("engine:manifest", payload),
  socialReformat: (payload: { text: string; projectPath?: string | null; targets: string[] }) => ipcRenderer.invoke("engine:reformat", payload),
  repurposeContent: (payload: unknown) => ipcRenderer.invoke("engine:repurpose", payload),
  postPackage: (payload: { text: string; projectPath?: string | null; videoPath: string; targets: string[]; title?: string | null }) => ipcRenderer.invoke("engine:postPackage", payload),
  postExportReview: (payload: unknown) => ipcRenderer.invoke("postExport:review", payload),
  postExportReexport: (payload: unknown) => ipcRenderer.invoke("postExport:reexport", payload),
  postExportTemplate: (payload: unknown) => ipcRenderer.invoke("postExport:template", payload),
  postExportVariants: (payload: unknown) => ipcRenderer.invoke("postExport:variants", payload),
  postExportNote: (payload: unknown) => ipcRenderer.invoke("postExport:note", payload),
  initBrandKit: () => ipcRenderer.invoke("brand:init"),
  applyBrandKit: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("brand:apply", payload),
  listTemplatePacks: () => ipcRenderer.invoke("templatePack:list"),
  exportTemplatePack: (payload: { template: string }) => ipcRenderer.invoke("templatePack:export", payload),
  installTemplatePack: () => ipcRenderer.invoke("templatePack:install"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings: unknown) => ipcRenderer.invoke("settings:save", settings),
  logFriction: (payload: unknown) => ipcRenderer.invoke("friction:log", payload),
  getFrictionReport: () => ipcRenderer.invoke("friction:report"),
  autosaveProject: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("recovery:autosave", payload),
  listRecovery: (payload: { projectPath?: string | null }) => ipcRenderer.invoke("recovery:list", payload),
  restoreRecovery: (payload: { sourcePath: string; targetPath?: string | null }) => ipcRenderer.invoke("recovery:restore", payload),
  getHardeningStatus: () => ipcRenderer.invoke("phase10:status"),
  workflowDashboard: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("workflow:dashboard", payload),
  getAdaptiveWorkflowMemory: (payload: { text?: string | null; projectPath?: string | null; profile?: string | null }) => ipcRenderer.invoke("workflow:adaptiveMemory", payload),
  recordAdaptiveWorkflowEvent: (payload: unknown) => ipcRenderer.invoke("workflow:adaptiveRecord", payload),
  feedbackAnalyze: (payload: { text: string; projectPath?: string | null; videoPath?: string | null }) => ipcRenderer.invoke("feedback:analyze", payload),
  feedbackReview: (payload: { text: string; projectPath?: string | null; videoPath?: string | null; profile?: string | null; note?: string | null; ratings?: Record<string, number> }) => ipcRenderer.invoke("feedback:review", payload),
  feedbackLearn: (payload: { profile: string }) => ipcRenderer.invoke("feedback:learn", payload),
  evolutionReport: (payload: { text: string; projectPath?: string | null; profile?: string | null; includeReleaseCheck?: boolean }) => ipcRenderer.invoke("evolution:report", payload),
  openLocalDocs: () => ipcRenderer.invoke("docs:open"),
  pickTranscript: () => ipcRenderer.invoke("transcript:pick"),
  importAssets: (payload: { projectPath?: string | null }) => ipcRenderer.invoke("assets:import", payload),
  checkAssets: (payload: { text: string; projectPath?: string | null }) => ipcRenderer.invoke("assets:check", payload),
  startRender: (payload: unknown) => ipcRenderer.invoke("render:start", payload),
  getRenderQueue: () => ipcRenderer.invoke("render:queue"),
  pauseRenderQueue: () => ipcRenderer.invoke("render:pause"),
  resumeRenderQueue: () => ipcRenderer.invoke("render:resume"),
  cancelRenderJob: (payload: { runId: string }) => ipcRenderer.invoke("render:cancel", payload),
  retryRenderJob: (payload: { runId: string }) => ipcRenderer.invoke("render:retry", payload),
  prioritizeRenderJob: (payload: { runId: string; priority: number }) => ipcRenderer.invoke("render:priority", payload),
  revealPath: (path: string) => ipcRenderer.invoke("shell:reveal", path),
  openOutputFolder: () => ipcRenderer.invoke("shell:openOutput"),
  toFileUrl: (path: string) => `file:///${path.replace(/\\/g, "/").replace(/ /g, "%20")}`,
  onRenderLog: (callback: (event: unknown) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
    ipcRenderer.on("render:log", listener);
    return () => ipcRenderer.removeListener("render:log", listener);
  },
  onRenderComplete: (callback: (event: unknown) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
    ipcRenderer.on("render:complete", listener);
    return () => ipcRenderer.removeListener("render:complete", listener);
  },
  onRenderQueue: (callback: (event: unknown) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
    ipcRenderer.on("render:queue", listener);
    return () => ipcRenderer.removeListener("render:queue", listener);
  }
});
